empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path



from .  import views
app_name="departamento_app"
urlpatterns = [
    path(
        "new_departamento/",
        views.NewDepartamentoView.as_view(),
        name="add_departamento"
        ),
    
    path(
        'dep_list/',
         views.DepartamentoListView.as_view(),
          name='lista_departamento'
          ),
   
]

empleado/applications/persona/urls.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria path
from django.urls import path
#Importar el archivo donde se encuentran las vistas
from .  import views
#----------------------------------------------------------------------------------------------



#--------------------------------------------URLS----------------------------------------------
#Etiqueta con la que se identifica el conjunto de urls
app_name="persona_app"

urlpatterns = [
    #Urls Template view (pagina comun) 
    path(
        "success/",
        views.SuccessView.as_view(),
        #nombre con el que se identificara la ruta
        name="correcto"
        ),
    #Urls y el nombre las vistas
    path('admin_empleado/',views.Lista_admin.as_view(), name='administrador'),

    path("lista_todo_empleado/",views.Listallempleados.as_view(),name="empleados_all"),
    path('api_lista_todo_empleado/', views.EmpleadolistAPIview.as_view(), name='api_all_empleados'),




    path("lista_by_key/",views.Listaempleadokey.as_view()),
    path("many_to_many/",views.Listamanytomany.as_view()),   
    #Url/variable que recibe la informacion en la url
    path("lista_by_area/<area>",views.Listarea.as_view(),name="area_empleados"),
    path("lista_by_job/<trabajo>",views.Listatrabajo.as_view()),
    
    #Url de una vista de detalle (detail view)
    path("detail_view_empleado/<pk>",views.EmpleadoDetailView.as_view(),name="detail_empleado"),
    
    
    #Url de una vista Create
    path(
        "create_empleado/",
        views.EmpleadoCreateView.as_view(),
        name="create_empleado"
        ),
    
    #Url de una vista updatevier
    path(
        "update_empleado/<pk>/",
        views.EmpleadoUpdateView.as_view(),
        name="update_empleado"
        ),
    #Url de una vista delete view
    path(
        "delete_empleado/<pk>/",
        views.EmpleadoDeleteView.as_view(),
        name="delete_empleado"
        ),
    #Url que carga la pagina principal
    path(
        '',
        views.InicioView.as_view(),
        name='home'
    ),

]
#----------------------------------------------------------------------------------------------

empleado/empleado/urls.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria para el administrador
from django.contrib import admin
#Path conexion
from django.urls import path,re_path, include
#Imagenes
from django.conf import settings
from django.conf.urls.static import static
#----------------------------------------------------------------------------------------------

    
#--------------------------------------------URLS----------------------------------------------
#URLS correspondientes a la carpeta applications
urlpatterns = [
    #Ruta del django admin
    path('admin/', admin.site.urls),
    #Incluimmos las urls de las apps de departamento
    re_path("",include("applications.departamento.urls")),
    re_path("",include("applications.persona.urls")),
    re_path("",include("applications.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #Imagenes multimedia cargarla 


#----------------------------------------------------------------------------------------------

empleado/templates/includes/headers.html
<div class="contain-to-grid fixed">
    
    <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
    </div>

    <div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li class="has-submenu">
            <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
<!--       <ul class="submenu menu vertical" data-submenu>
            <li><a href="#0">Listar</a></li>
            <li><a href="#0"></a></li>
            <li><a href="#0">Three</a></li>
            </ul>-->
        </li>
        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'departamento_app:add_departamento' %}">Agregar Departamento</a></li>
        <li><a href="{% url 'persona_app:administrador' %}">Administrar</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:create_empleado' %}" class="button" type="button" >Registrar nuevo empleado</a></li>
        
        </ul>
    </div>
    </div>
</div>


  