empleado/applications/persona/urls.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria path
from django.urls import path
#Importar el archivo donde se encuentran las vistas
from .  import views
#----------------------------------------------------------------------------------------------



#--------------------------------------------URLS----------------------------------------------
#Etiqueta con la que se identifica el conjunto de urls
app_name="persona_app"

urlpatterns = [
    #Urls Template view (pagina comun) 
    path(
        "success/",
        views.SuccessView.as_view(),
        #nombre con el que se identificara la ruta
        name="correcto"
        ),
    #Urls y el nombre las vistas
    path('admin_empleado/',views.Lista_admin.as_view(), name='administrador'),

    path("lista_todo_empleado/",views.Listallempleados.as_view(),name="empleados_all"),
    path('api_lista_todo_empleado/', views.EmpleadolistAPIview.as_view(), name='api_all_empleados'),




    path("lista_by_key/",views.Listaempleadokey.as_view()),
    path("many_to_many/",views.Listamanytomany.as_view()),   
    #Url/variable que recibe la informacion en la url
    path("lista_by_area/<area>",views.Listarea.as_view(),name="area_empleados"),
    path("lista_by_job/<trabajo>",views.Listatrabajo.as_view()),
    
    #Url de una vista de detalle (detail view)
    path("detail_view_empleado/<pk>",views.EmpleadoDetailView.as_view(),name="detail_empleado"),
    
    
    #Url de una vista Create
    path(
        "create_empleado/",
        views.EmpleadoCreateView.as_view(),
        name="create_empleado"
        ),
    
    #Url de una vista updatevier
    path(
        "update_empleado/<pk>/",
        views.EmpleadoUpdateView.as_view(),
        name="update_empleado"
        ),
    #Url de una vista delete view
    path(
        "delete_empleado/<pk>/",
        views.EmpleadoDeleteView.as_view(),
        name="delete_empleado"
        ),
    #Url que carga la pagina principal
    path(
        '',
        views.InicioView.as_view(),
        name='home'
    ),

]
#----------------------------------------------------------------------------------------------

empleado/empleado/urls.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria para el administrador
from django.contrib import admin
#Path conexion
from django.urls import path,re_path, include
#Imagenes
from django.conf import settings
from django.conf.urls.static import static
#----------------------------------------------------------------------------------------------

    
#--------------------------------------------URLS----------------------------------------------
#URLS correspondientes a la carpeta applications
urlpatterns = [
    #Ruta del django admin
    path('admin/', admin.site.urls),
    #Incluimmos las urls de las apps de departamento
    re_path("",include("applications.departamento.urls")),
    re_path("",include("applications.persona.urls")),
    re_path("",include("applications.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #Imagenes multimedia cargarla 


#----------------------------------------------------------------------------------------------

empleado/applications/persona/models.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria models ORM
from django.db import models
#Base de datos a la cual se hace referencia
from applications.departamento.models import Departamento
#Aplicaciones de terceros()
from ckeditor.fields import RichTextField
#----------------------------------------------------------------------------------------------

#---------------------------------------MODELO 1-----------------------------------------------
# Create your models here.
#Tabla de habilidades 
class Habilidad(models.Model):
    #El id es un campo que se agrega de manera automatica
    habilidad = models.CharField("Habilidad", max_length=100)
    #Clase meta modifica las vistas de Django admin dentro de esta tabla
    class Meta:
        verbose_name="Habilidad"
        verbose_name_plural="Habilidades"
        ordering=["id"]  
    #La funcion __str__ es el mensaje de salida que tendra la tabla Habilidad    
    def __str__(self):
        return str(self.id)+" "+self.habilidad
#----------------------------------------------------------------------------------------------        

#---------------------------------------MODELO 2-----------------------------------------------
#Tabla de empleados
class Empleado(models.Model):
    JOB_CHOICES=(
        ("0","CONTADOR"),
        ("1","ADMINISTRADOR"),
        ("2","ECONOMISTA"),
        ("3","OTRO"),
    )    
    
    first_name = models.CharField("Nombres", max_length=50)
    last_name = models.CharField("Apellidos", max_length=50)
    full_name = models.CharField("Nombre completo", max_length=120,blank=True)
    #Hace referencia a la lista de opciones JOB_CHOICES
    job = models.CharField("Trabajo", max_length=50,choices=JOB_CHOICES)
    #llAVE FORANEA
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    #Imagen
    image = models.ImageField( upload_to="empleado", blank=True,null=True)
    #Relacion de muchos a muchos
    habilidades = models.ManyToManyField("Habilidad")
    #Aplicacion de terceros (ckeditor)
    hoja_vida= RichTextField("Hoja de vida")

    #Clase meta modifica las vistas de Django admin dentro de esta tabla
    class Meta:
        verbose_name="Persona"
        verbose_name_plural="Personas"
        ordering=["id"] 
        #Coincidencias que no deben repetirse 
        unique_together=["first_name","job"]

    #La funcion __str__ es el mensaje de salida que tendra la tabla Empleado 
    def __str__(self):
        return str(self.id)+" "+self.first_name+" "+self.last_name
#---------------------------------------------------------------------------------------------- 

empleado/applications/persona/forms.py
from tkinter import Widget
from django import forms
from .models import Empleado

class PersonForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'image',
            'habilidades',
            'hoja_vida',
            )
        widgets={
            "habilidades" :forms.CheckboxSelectMultiple()
        }

empleado/applications/persona/views.py
#---------------------------------------LIBRERIAS---------------------------------------------
#BASE DE DATOS EMPLEADO

import imp
from .models import Empleado
# Create your views here.
#IMPORTAR FORMS
from .forms import EmpleadoForm
#IMPORTA VISTAS GENERICAS
from django.views.generic import ListView,DetailView,CreateView,TemplateView,UpdateView,DeleteView
#VISTAS PARA APIS
from rest_framework.generics import ListAPIView
#Importa redireccionamiento de urls
from django.urls import reverse_lazy
#----------------------------------------------------------------------------------------------
#---------------------------------------VISTA 0------------------------------------------------
#Vista que enlista todos los empleados de la tabla empleados (CRUD)
class Lista_admin(ListView):
    #Template donde se pintara la informacion
    template_name= "persona/administradorempleados.html"
    paginate_by=5
    #Ordenar
    ordering="id"
    model=Empleado
    context_object_name="admin_empleados"




#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 1------------------------------------------------
#Vista que enlista todos los empleados de la tabla empleados
class Listallempleados(ListView):
    #Template donde se pintara la informacion
    template_name= "persona/listall.html"
    #Paginacion 
    #Agregar en la url /?page=1 y mostrara la informacion de esa pagina
    paginate_by=5
    #Ordenar
    ordering="id"
    #informacion de la base empleado que se mostrara
    #model=Empleado
    #Variable que se debe pintar en el archivo html
    #context_object_name= "lista_empleados"
    def get_queryset(self):
      
        #Obtiene la informacion del formulario con metodo Get
        palabra_clave=self.request.GET.get("kword", "")

        #Compara la informacion recibida en el input con la de la base
        lista=Empleado.objects.filter(full_name__icontains=palabra_clave)
        return lista

#API
from .serializers import EmpleadoSerializer
class EmpleadolistAPIview(ListAPIView):
    #formato json
    serializer_class=EmpleadoSerializer
    def get_queryset(self):
        
        return Empleado.objects.all()
    #serializar
#----------------------------------------------------------------------------------------------
    


#---------------------------------------VISTA 2------------------------------------------------
#Vista que enlista todos los empleados por area determinada
class Listarea(ListView):
    #Template donde se pintara la informacion
    template_name= "persona/listarea.html"
    context_object_name="empleado_area"
    
    #Funcion que recibe informacion mediante la URL
    def get_queryset(self):
        #Variable que almacena el valor ingresador en la URL
        #Recibe un parametro mediante una url
        area=self.kwargs["area"]
        #Compara la informacion recibida en la url con la de la base
        lista=Empleado.objects.filter(departamento__shortname=area)
        return lista
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 3------------------------------------------------
#Vista que filtra al empleado mediante el "trabajo" 
#Recordar que lo que se ingresara en la url sera el numero correspondiente al empleado
class Listatrabajo(ListView):
    #Template donde se pintara la informacion
    template_name= "persona/listatrabajo.html"
    
    def get_queryset(self):
        #Variable que almacena el valor ingresador en la URL
        #Recibe un parametro mediante una url
        trabajo=self.kwargs["trabajo"]
        #Compara la informacion recibida en la url con la de la base
        lista=Empleado.objects.filter(job=trabajo)
        return lista
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 4------------------------------------------------
#Genera una busqueda en la tabla empleados mediante una caja de texto
class Listaempleadokey(ListView):
    #Template donde se pintara la informacion
    template_name="persona/listaempleadokey.html"
    #Objeto que envia la informacion al html
    context_object_name= "empleados"

    #Funcion que recibe la informacion desde una caja de texto desde el html
    def get_queryset(self):
        print("*******")
        #Obtiene la informacion del formulario con metodo Get
        palabra_clave=self.request.GET.get("kword", "")
        print("*********",palabra_clave)
        #Compara la informacion recibida en el input con la de la base
        lista=Empleado.objects.filter(first_name=palabra_clave)
        return lista
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 5------------------------------------------------
#Listview  con relacion de muchos a muchos
class Listamanytomany(ListView):
    template_name="persona/manytomany.html"
    context_object_name="habilidades"

    def get_queryset(self):

        lista=Empleado.objects.get(id=1)
        #Objeto que almacena el empleado y sus habilidades correspondientes
        empleado_habilidades=lista.habilidades.all()
        return empleado_habilidades
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 6------------------------------------------------
 #DETAIL VIEW

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/empleadodetail.html"

    def get_context_data(self, **kwargs) :
        context=super(EmpleadoDetailView,self).get_context_data(**kwargs)
        #context["titulo"]="Empleado del mes"
        return context
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 7------------------------------------------------

class SuccessView(TemplateView):
    template_name = "persona/success.html"


#CREATE VIEW (POST)
#Recuerda que el objeto con el que se pintara la informacion en el htlm es "form"
class EmpleadoCreateView(CreateView):
    #Modelo
    model = Empleado
    #Template
    template_name = "persona/crearempleado.html"
    form_class= EmpleadoForm
    #Campos
    #fields=["first_name","last_name","job","departamento","departamento","image","habilidades","hoja_vida"]
    #fields=("__all__")
#------------------------------------------------------------------------------------------
 #REDIRECCIONAMIENTO NO RECOMENDADO   
    #Pagina que rediccionara cuando la vista cumpla su cometido "."= el mismo template
    #Url no template
    #success_url= "/success"
#------------------------------------------------------------------------------------------    
#REDIRECCIONAMIENTO CON DJANGO 
# libreria reverse_lazy
#   persona_app (etiqueta de las urls) correcto (name de la url)   
    success_url=reverse_lazy("persona_app:administrador")

    def form_valid(self, form):
        '''
        Cuando lo recibido en el formulario es correcto
        '''
        #Almacena la informacion en la base (Intercepta la informacion guardada)
        empleado=form.save(commit=False)
        print(empleado)
        #Actualiza uno de los campos con la informacion registrada
        empleado.full_name=empleado.first_name +" "+empleado.last_name
        #Actualiza la informacion en la base
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 7------------------------------------------------
#UPDATE VIEW
class EmpleadoUpdateView(UpdateView):
    #Similar al CREATE VIEW
    model = Empleado
    template_name = "persona/empleadoupdate.html"
    fields=["first_name","last_name","job","departamento","departamento","image","habilidades","hoja_vida"]
    success_url=reverse_lazy("persona_app:administrador")

    '''
    def post(self, request, *args, **kwargs):
        
        Esta funcion se ejecuta primero
        Permite obtener los datos desde el la url con request
        
        print("+++++++++++++METODO POST+++++++++++++++++")
        print(request.POST)
        print(request.POST["full_name"])
        print("*****************************************")
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
        '''

    def form_valid(self, form):
        print("+++++++++++++METODO FORM VALID+++++++++++++++++")
        '''
        Cuando lo recibido en el formulario es correcto
        '''
        #Almacena la informacion en la base (Intercepta la informacion guardada)
        empleado=form.save(commit=False)
        print(empleado)
        #Actualiza uno de los campos con la informacion registrada
        empleado.full_name=empleado.first_name +" "+empleado.last_name
        #Actualiza la informacion en la base
        empleado.save()
        return super(EmpleadoUpdateView,self).form_valid(form)
#----------------------------------------------------------------------------------------------

#---------------------------------------VISTA 8------------------------------------------------
#DELETE VIEW

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/deletepersona.html"
    success_url=reverse_lazy("persona_app:administrador")


#------------------------------------------------------------------------------------------------
#---------------------------------------VISTA INICIO---------------------------------------------

class InicioView(TemplateView):
    '''
    Esta vista carga la pantalla de inicio
    '''  
    template_name = "inicio.html"

empleado/templates/persona/administradorempleados.html
{% extends 'base.html' %}

{% block titulo %}
    Administrar empleados
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}
<div class="grid-container ">
    <div class="grid-x">
        <h1 class="cell">Administrar empleados</h1>



        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="100">ID</th>
                    <th width="100">Nombres</th>
                    <th width="100">Apellidos</th>
                    <th width="100">Departamento</th>
                    <th width="100">Accion</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in admin_empleados %}
                  <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td>
                        <a class="button warning" href="{% url 'persona_app:update_empleado' e.id %}">Editar</a>
                        <a class="button alert" href="{% url 'persona_app:delete_empleado' e.id %}">Eliminar</a>
                    
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>











            
          
            <!--Fin listar empleados-->

        </div>

<!--Inicio paginacion--->
        <div class="cell">
            
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination text-center">
                    
                    
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous "><a href="?page={{ page_obj.previous_page_number}}" aria-label="Previous page"> Atras<span class="show-for-sr">page</span> </a> </li>
                        {% endif %}
                        
                        
                        {% for pag in paginator.page_range  %}
                            
                        {% if pag == page_obj.number %} 
                                <li class="current"><span class="show-for-sr">You're on page</span> {{pag}}</li>
                        {% else %}      
                                <li><a href="?page={{pag}}" aria-label="Page 2">{{pag}}</a></li>
                        {% endif %}
                        {% endfor %}
                            
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next"><a href="?page={{ page_obj.next_page_number}}" aria-label="Next page">Siguiente <span class="show-for-sr">page</span></a></li>
                        {% endif %}
                    </ul>
                </nav>
                    
            {% endif %}
                
            
        </div>
 <!--Fin paginacion--->       
    </div>
    



</div>

{% endblock content %}

    

empleado/templates/persona/crearempleado.html
{% extends 'base.html' %}

{% block titulo %}
    Crear empleado
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}
<div class="grid-container">
    <div class="grid-x ">
        <h1 class="cell">
            <h1>Crear empleado</h1>

        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="cell large-6">
                    <label>Nombre
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellido
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Imagen
                        {{form.image}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Hoja de vida
                        {{form.hoja_vida}}
                    </label>
                </div>
                <div class="cell large-6">
                    <button class="button success" type="submit" >Guardar</button>
                    
                  </div>

                
                
            </form>
        </div>
      
    </div>
</div>


    
   
    
{% endblock content %}
    

empleado/templates/persona/deletepersona.html
{% extends 'base.html' %}

{% block titulo %}
    Eliminar empleado
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}
   <div class="grid-container">
       <div class="grid-x">
           <h1 class="cell">
            Eliminar empleado
           </h1>
           <div class="cell">
            <form method="POST">
                {% csrf_token %}
                <div class="callout alert">
                    <h5>Confirme que desea eliminar al empleado {{object.first_name}}</h5>
                  </div>
                
                <button class="button alert" type="submit" >Eliminar</button>
                
        
            </form>
            
           </div>
           
       </div>
   </div> 
{% endblock content %}


    

empleado/templates/persona/empleadodetail.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
    Detalle empleados
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 

{% endblock headers %}
    
    

{% block content %}
<div  class="grid-container aling-center"></div>
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-3  card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider align-center">
                <h4>Datos del empleado {{object.id }}</h4>
                
            </div>
            <div class="card-divider align-center">
                
                {{empleado.first_name}} {{empleado.last_name}}
            </div>
            {% if empleado.image %}
                <img src="{{empleado.image.url}}">   
            {% else %}
                <img src="{% static 'img/fail.jpg' %}">  
            {% endif %}
                    
        <div class="card-section">

            <p>Trabajo:{{object.get_job_display}}</p>
            <p>Departamento:{{object.departamento.shortname}}</p>
            <p><span class="label">habilidades</span></p>
            <ul class="vertical menu">
                
                {% for h in object.habilidades.all %}
                    <li>{{h.habilidad}}</li>
                    
                {% endfor %}
                    
            </ul>  
            <div class="cell">
                {{object.hoja_vida}}
            </div>
            
            
            </div>
        </div>




    </div>


   
    
  

    {% endblock content %}

empleado/templates/persona/empleadoupdate.html
{% extends 'base.html' %}

{% block titulo %}
    Actualizar empleados
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}
<div class="grid-container">
<div class="grid-x">
    <h1 class="cell">
        Actualizar empleados
    </h1>

    <div class="cell">
        <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6">
                <label>Nombre
                    {{form.first_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Apellido
                    {{form.last_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Trabajo
                    {{form.job}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Departamento
                    {{form.departamento}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Imagen
                    {{form.image}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Habilidades
                    {{form.habilidades}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Hoja de vida
                    {{form.hoja_vida}}
                </label>
            </div>
            <div class="cell large-6">
                <button class="button success" type="submit" >Actualizar</button>
                
              </div>

            
            
            
        
        </form>
    </div>
</div>
</div>


{% endblock content %}
    
    

empleado/templates/persona/listaempleadokey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Buscar empleados por palabra clave</h1>

    <!---Formulario que hara una peticion Get a la base -->
    <form  method="GET">
        <!--Comunicacion segura(Oculta la informacion en la url)-->
        {% csrf_token %}
        <!--Caja de texto-->
        <input type= "text"id="kword" name="kword" placeholder="Ingresa el nombre">
        <!--Boton-->
        <button type="submit">Buscar</button>

    </form>
<!-------------------------------------------------------------------------------------------------->
    <h3>Lista de resultados</h3>
    <!--"empleados es el objeto de tipo context_object_name declarado en la vista generica"-->
    {% for e in empleados %}
        <li>{{e}}</li>  
    {% endfor %}
</body>
</html>

empleado/templates/persona/listall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Empleado</title>
</head>
<body>
    <h1>Apartado para los empleados</h1>

    <!--"object_list" es el objeto que almacena por dafault la
    informacion que proviene del archivo views.py-->
    {% for e in object_list %}
        <li>{{e}}</li>
        
    {% endfor %}
        
</body>
</html>

empleado/templates/persona/listarea.html
{% extends 'base.html' %}

{% block titulo %}
    Empleados por area
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}
<div class="grid-container ">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>


        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="100">ID</th>
                    <th width="100">Nombres</th>
                    <th width="100">Apellidos</th>
                    <th width="100">Departamento</th>
                    <th width="100">Accion</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in empleado_area %}
                  <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button success" href="{% url 'persona_app:detail_empleado' e.id %}">Ver</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            <!--Fin listar empleados-->

        </div>



    
{% endblock content %}
    
    

empleado/templates/persona/listatrabajo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trabajo</title>
</head>
<body>
    <h1>Filtra la tabla por  "Trabajo</h1>
    <!--"object_list" es el objeto que almacena por dafault la
    informacion que proviene del archivo views.py-->
    {% for e in object_list %}
        <li>{{e}}</li>
    
    {% endfor %}
</body>
</html>

empleado/templates/persona/manytomany.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Many to many</title>
</head>
<body>
    <h1> Lista de muchos a muchos</h1>

    <!---Formulario que hara una peticion Get a la base -->
    <form  method="GET">
        <!--Comunicacion segura(Oculta la informacion en la url)-->
        <!--{% csrf_token %}-->
        <!--Caja de texto-->
        <input type= "text"id="id_empleado" name="id_empleado" placeholder="Ingresa el nombre">
        <!--Boton-->
        <button type="submit">Buscar</button>

    </form>
<!-------------------------------------------------------------------------------------------------->
    <h3>Lista de resultados</h3>
    <!--"empleados es el objeto de tipo context_object_name declarado en la vista generica"-->
    
    {% for e in habilidades %}
        <li>{{e}}</li>  
    {% endfor %}
</body>
</html>

empleado/templates/persona/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <h1>Operacion exitosa  {{dele}}</h1>
    
</body>
</html>