empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path



from .  import views
app_name="departamento_app"
urlpatterns = [
    path(
        "new_departamento/",
        views.NewDepartamentoView.as_view(),
        name="add_departamento"
        ),
    
    path(
        'dep_list/',
         views.DepartamentoListView.as_view(),
          name='lista_departamento'
          ),
   
]

empleado/applications/persona/urls.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria path
from django.urls import path
#Importar el archivo donde se encuentran las vistas
from .  import views
#----------------------------------------------------------------------------------------------



#--------------------------------------------URLS----------------------------------------------
#Etiqueta con la que se identifica el conjunto de urls
app_name="persona_app"

urlpatterns = [
    #Urls Template view (pagina comun) 
    path(
        "success/",
        views.SuccessView.as_view(),
        #nombre con el que se identificara la ruta
        name="correcto"
        ),
    #Urls y el nombre las vistas
    path('admin_empleado/',views.Lista_admin.as_view(), name='administrador'),

    path("lista_todo_empleado/",views.Listallempleados.as_view(),name="empleados_all"),
    path('api_lista_todo_empleado/', views.EmpleadolistAPIview.as_view(), name='api_all_empleados'),




    path("lista_by_key/",views.Listaempleadokey.as_view()),
    path("many_to_many/",views.Listamanytomany.as_view()),   
    #Url/variable que recibe la informacion en la url
    path("lista_by_area/<area>",views.Listarea.as_view(),name="area_empleados"),
    path("lista_by_job/<trabajo>",views.Listatrabajo.as_view()),
    
    #Url de una vista de detalle (detail view)
    path("detail_view_empleado/<pk>",views.EmpleadoDetailView.as_view(),name="detail_empleado"),
    
    
    #Url de una vista Create
    path(
        "create_empleado/",
        views.EmpleadoCreateView.as_view(),
        name="create_empleado"
        ),
    
    #Url de una vista updatevier
    path(
        "update_empleado/<pk>/",
        views.EmpleadoUpdateView.as_view(),
        name="update_empleado"
        ),
    #Url de una vista delete view
    path(
        "delete_empleado/<pk>/",
        views.EmpleadoDeleteView.as_view(),
        name="delete_empleado"
        ),
    #Url que carga la pagina principal
    path(
        '',
        views.InicioView.as_view(),
        name='home'
    ),

]
#----------------------------------------------------------------------------------------------

empleado/empleado/urls.py
#---------------------------------------LIBRERIAS---------------------------------------------
#Libreria para el administrador
from django.contrib import admin
#Path conexion
from django.urls import path,re_path, include
#Imagenes
from django.conf import settings
from django.conf.urls.static import static
#----------------------------------------------------------------------------------------------

    
#--------------------------------------------URLS----------------------------------------------
#URLS correspondientes a la carpeta applications
urlpatterns = [
    #Ruta del django admin
    path('admin/', admin.site.urls),
    #Incluimmos las urls de las apps de departamento
    re_path("",include("applications.departamento.urls")),
    re_path("",include("applications.persona.urls")),
    re_path("",include("applications.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #Imagenes multimedia cargarla 


#----------------------------------------------------------------------------------------------

empleado/applications/departamento/models.py
from msilib import make_id
from tabnanny import verbose
from unicodedata import name
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField("Nombre",max_length=50)
    shortname = models.CharField("Nombre corto", max_length=20,unique=True)
    status = models.BooleanField("Anulado",default=False)

    class Meta:
        verbose_name="Departamento"
        verbose_name_plural="Departamentos"
        ordering=["id"]
        unique_together=["name","shortname"]

    
    def __str__(self):
        return self.name

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField( max_length=50)
    apellidos = forms.CharField( max_length=50)
    departamento = forms.CharField( max_length=50)
    shortname = forms.CharField(max_length=20)

empleado/applications/departamento/views.py
#----------------------------FORM VIEW------------------------------------------





# Create your views here.
#Form view
from django.views.generic.edit import FormView
from django.views.generic import ListView


from .forms import NewDepartamentoForm
#Tablas que se usaran para hacer ls insercion
from applications.persona.models import Empleado
from .models import Departamento


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/dep_list_view.html"
    context_object_name="departamentos"




#-------------------------------------------------------------------------------------------------
class NewDepartamentoView(FormView):
    template_name="departamento/new_departamento.html"
    form_class=NewDepartamentoForm
    success_url="/"

    def form_valid(self,form):
        '''
        recupera la informacion del formulario 
        y lo ingresa en dos tablas diferentes
        '''
       
        depa=Departamento(
            name=form.cleaned_data["departamento"],
            shortname=form.cleaned_data["shortname"],
            )
        depa.save()


        name=form.cleaned_data["nombre"]
        last_name=form.cleaned_data["apellidos"]
        Empleado.objects.create(first_name=name,
                                last_name=last_name,
                                job="1",
                                #iguala el valor de este campo a lo que se ingreso en departamento
                                departamento=depa)
        
        return super(NewDepartamentoView,self).form_valid(form)

empleado/templates/departamento/dep_list_view.html
{% extends 'base.html' %}

{% block titulo %}
    Lista de departamentos
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}
<div class="grid-container">
    <div  class="grid-x">
        <h1 class="cell">Hola mundo</h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for dep in departamentos %}
                    <tr>
                        <td>{{dep.name}}</td>
                        <td>{{dep.shortname}}</td>
                        <td><a class="button success" href="{% url 'persona_app:area_empleados' dep.shortname %}">Ver empleados</a></td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
 
{% endblock content %}
    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block titulo %}
    Nuevo departamento
{% endblock titulo %}


{% block headers %}
{% include 'includes/headers.html' %} 
{% endblock headers %}
    
    

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Agregar departamento</h1>
            </div>
            <div class="cell">
                <h3>Datos empleados</h3>
                
                <p> Nombre:{{form.nombre}}</p>
                <p>Apellido:{{form.apellidos}}</p>
            </div>
            <div class="cell">
                <h3>Datos del departamento</h3>
                <p>Nombre dep:{{form.departamento}}</p>
                <p>Dep nombre corto:{{form.shortname}}</p>
            </div>
            <div class="cell">
                <button class="button success" type="submit" >Guardar</button>

            </div>
        </div>
    </div>
        
</form>

    
{% endblock content %}
    
    